---
functional: | 
  - поиск товара по категории 
  - фильтровать товар по цвету, цене, размеру 
  - возможность просматривать товар и информацию о товаре 
  - возможность добавлять товар в корзину
non-functional: |
  - удобство использования веб-сайта
  - сайт должен быть безопасен
  - пользовательские данные защищены
  - сайт должен иметь мобильную версию
  - сайт должен быть доступен на различных устройствах
implicit: |
  - как удалить товар из корзины
  - как товар попадает к покупателю
  - как производится оплата
  - контактные данные магазина
  - личный кабинет
